#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND   "SatyrDiamond"
#define DISTRHO_PLUGIN_NAME    "DVc LMMS Amplifier"
#define DISTRHO_PLUGIN_URI     ""
#define DISTRHO_PLUGIN_CLAP_ID "satyrdiamond.lmms_fx.dvc_lmms_amplifier"

#define DISTRHO_PLUGIN_HAS_UI        0
#define DISTRHO_PLUGIN_IS_RT_SAFE    1
#define DISTRHO_PLUGIN_NUM_INPUTS    2
#define DISTRHO_PLUGIN_NUM_OUTPUTS   2
#define DISTRHO_PLUGIN_WANT_PROGRAMS 1

#define DISTRHO_PLUGIN_CLAP_FEATURES "audio-effect"
#define DISTRHO_PLUGIN_LV2_CATEGORY "lv2"
#define DISTRHO_PLUGIN_VST3_CATEGORIES "Fx"

#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED
